# Funding information for SARAi_AGI
# https://github.com/iagenerativa/sarai-agi

# You can add funding platforms here
# github: [iagenerativa]
# patreon: username
# open_collective: project-name
# custom: ["https://yoursite.com/donate"]
